# Generated by Django 4.0.5 on 2022-10-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/Profile/images/default-user.png', null=True, upload_to='avatars/'),
        ),
    ]
