# Generated by Django 4.0.5 on 2022-10-12 06:54

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default=Profile.models.get_default_avatar, null=True, upload_to=Profile.models.get_avatar_filepath),
        ),
    ]
