# Generated by Django 4.0.5 on 2022-10-13 08:14

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default=Blog.models.get_default_thumbnail, null=True, upload_to=Blog.models.get_thumbnail_filepath),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Blog.models.get_post_image_filepath),
        ),
    ]
